### ISSUE TITLE
1st stage work_ configuration

### ISSUE THREAD

**Issue by ruijis** [ruijis/info290_dbt#1]
- [x] install dbt locally or just use class JupyterLab
https://docs.getdbt.com/dbt-cli/installation

- [x] Yash - set up .dbt/profiles.yml and connect to Berkeley buildings database
https://docs.getdbt.com/dbt-cli/configure-your-profile

**Comment by yb4** [comment]
Completed the profiles.yml page. Note that you can initialize git repo on datahub and work from there. Please read a point added on Readme (will be available on git push updates).
